/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SidebarMemoryPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_DATA = {
  noteStates: {}
};
var SidebarMemoryPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    // 上一个活动的笔记路径，用于在切换前保存其状态
    this.previousFilePath = null;
    // 防止在我们自己调整 sidebar 时触发保存逻辑
    this.isApplyingState = false;
    // 防抖定时器
    this.saveTimer = null;
  }
  async onload() {
    await this.loadData();
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        this.handleLeafChange(leaf);
      })
    );
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        if (!this.isApplyingState) {
          this.debouncedSaveCurrentState();
        }
      })
    );
    this.addSettingTab(new SidebarMemorySettingTab(this.app, this));
    console.log("SidebarMemory: Plugin loaded");
  }
  onunload() {
    if (this.saveTimer) {
      clearTimeout(this.saveTimer);
    }
  }
  handleLeafChange(leaf) {
    if (this.isApplyingState)
      return;
    const currentFile = this.app.workspace.getActiveFile();
    if (!currentFile) {
      if (this.previousFilePath) {
        this.saveStateForFile(this.previousFilePath);
      }
      this.previousFilePath = null;
      return;
    }
    const currentPath = currentFile.path;
    if (currentPath === this.previousFilePath)
      return;
    if (this.previousFilePath) {
      this.saveStateForFile(this.previousFilePath);
    }
    this.restoreStateForFile(currentPath);
    this.previousFilePath = currentPath;
  }
  saveStateForFile(filePath) {
    const state = this.getCurrentSidebarState();
    this.data.noteStates[filePath] = state;
    this.saveData(this.data);
  }
  restoreStateForFile(filePath) {
    const savedState = this.data.noteStates[filePath];
    if (savedState === void 0) {
      return;
    }
    this.isApplyingState = true;
    try {
      this.applySidebarState(savedState);
    } finally {
      setTimeout(() => {
        this.isApplyingState = false;
      }, 200);
    }
  }
  getCurrentSidebarState() {
    const leftOpen = !this.app.workspace.leftSplit.collapsed;
    const rightOpen = !this.app.workspace.rightSplit.collapsed;
    return { leftOpen, rightOpen };
  }
  applySidebarState(state) {
    const leftSplit = this.app.workspace.leftSplit;
    const rightSplit = this.app.workspace.rightSplit;
    const leftCurrentlyOpen = !leftSplit.collapsed;
    const rightCurrentlyOpen = !rightSplit.collapsed;
    if (state.leftOpen !== leftCurrentlyOpen) {
      if (state.leftOpen) {
        leftSplit.expand();
      } else {
        leftSplit.collapse();
      }
    }
    if (state.rightOpen !== rightCurrentlyOpen) {
      if (state.rightOpen) {
        rightSplit.expand();
      } else {
        rightSplit.collapse();
      }
    }
  }
  debouncedSaveCurrentState() {
    if (this.saveTimer) {
      clearTimeout(this.saveTimer);
    }
    this.saveTimer = setTimeout(() => {
      const currentFile = this.app.workspace.getActiveFile();
      if (currentFile) {
        this.saveStateForFile(currentFile.path);
        this.previousFilePath = currentFile.path;
      }
    }, 300);
  }
  async loadData() {
    const loaded = await super.loadData();
    this.data = Object.assign({}, DEFAULT_DATA, loaded);
    if (!this.data.noteStates) {
      this.data.noteStates = {};
    }
  }
  async saveData(data) {
    await super.saveData(data);
  }
  /**
   * 清除某个笔记的状态记录
   */
  clearStateForFile(filePath) {
    delete this.data.noteStates[filePath];
    this.saveData(this.data);
  }
  /**
   * 清除所有笔记的状态记录
   */
  clearAllStates() {
    this.data.noteStates = {};
    this.saveData(this.data);
  }
};
var SidebarMemorySettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Sidebar Memory" });
    containerEl.createEl("p", {
      text: "\u81EA\u52A8\u8BB0\u4F4F\u6BCF\u4E2A\u7B14\u8BB0\u7684\u4FA7\u8FB9\u680F\u6253\u5F00/\u5173\u95ED\u72B6\u6001\uFF0C\u5207\u6362\u7B14\u8BB0\u65F6\u81EA\u52A8\u8FD8\u539F\u3002",
      cls: "setting-item-description"
    });
    const count = Object.keys(this.plugin.data.noteStates).length;
    containerEl.createEl("p", {
      text: `\u5F53\u524D\u5DF2\u8BB0\u5F55 ${count} \u4E2A\u7B14\u8BB0\u7684\u4FA7\u8FB9\u680F\u72B6\u6001\u3002`,
      cls: "setting-item-description"
    });
    new import_obsidian.Setting(containerEl).setName("\u6E05\u9664\u5F53\u524D\u7B14\u8BB0\u72B6\u6001").setDesc("\u5220\u9664\u5F53\u524D\u6253\u5F00\u7B14\u8BB0\u7684\u4FA7\u8FB9\u680F\u8BB0\u5FC6\uFF0C\u4E0B\u6B21\u6253\u5F00\u65F6\u4E0D\u4F1A\u81EA\u52A8\u8C03\u6574\u4FA7\u8FB9\u680F\u3002").addButton((button) => button.setButtonText("\u6E05\u9664\u5F53\u524D\u7B14\u8BB0").setWarning().onClick(() => {
      const file = this.plugin.app.workspace.getActiveFile();
      if (file) {
        this.plugin.clearStateForFile(file.path);
        this.display();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("\u6E05\u9664\u6240\u6709\u8BB0\u5F55").setDesc("\u5220\u9664\u6240\u6709\u7B14\u8BB0\u7684\u4FA7\u8FB9\u680F\u8BB0\u5FC6\uFF0C\u91CD\u65B0\u5F00\u59CB\u8BB0\u5F55\u3002").addButton((button) => button.setButtonText("\u6E05\u9664\u5168\u90E8").setWarning().onClick(() => {
      this.plugin.clearAllStates();
      this.display();
    }));
  }
};
